### ISSUE TITLE
Use cmd.exe on Windows

### ISSUE THREAD

**Issue by adamralph** [adamralph/simple-exec#100]
As [discussed](https://ddd-cqrs-es.slack.com/archives/C3GTBRMS7/p1546359264036100).

Relates to https://github.com/adamralph/simple-exec/issues/99

**Comment by adamralph** [comment]
Released in [alpha 1](https://www.nuget.org/packages/SimpleExec/5.0.0-alpha.1).

**Comment by damianh** [comment]
Will give it a kick. Might have to adopt similar in LittleForker.

**Comment by adamralph** [comment]
@damianh did you get a chance to try this out? I wanted to send a PR to SQLStreamStore, but the yarn command doesn't run as part of the CI build, and I don't have yarn on my machine to try it, so my PR wouldn't prove anything.

**Comment by damianh** [comment]
Works locally (windows) and works in CI (linux container). Go go go

**Comment by adamralph** [comment]
Awesome @damianh, thanks!
