### ISSUE TITLE
Quazi-"tee" option for Read[Async]() and callbacks.

### ISSUE THREAD

**Issue by ygel** [adamralph/simple-exec#141]
Hi, using simpleexec with bullseye, would be nice to have optionally Read/ReadAsync "tee" output into respective streams, as well as return data.

Also, what do you think about optional user-provided callback to "stream" data to the caller as it arrives? This would probably best be implemented on Run/RunAsync.
Use-case: one of the commands I run, prints name of the artifact it produces, would like to pick it up from there, as well as have it in the CI logs, which are read from stdout/stderr.

**Comment by adamralph** [comment]
Hi @ygel, thank for raising this.

Regarding your use case, would I be correct in assuming that you could work around this today by doing this?

```c#
var output = Read("foo");
Console.Out.WriteLine(output);
// use output for something else
```

**Comment by ygel** [comment]
It's possible but not desired. For CI runs with lots of log output I'd like to keep memory usage down and be able to see the log text stream as its being sent.

**Comment by adamralph** [comment]
OK, I see. I'll have a play and see what might fit.

**Comment by ygel** [comment]
Here's an outline of the approach I used before, ripped out from an old app, so will not build as-is.
https://gist.github.com/ygel/336fe6266346869bf675b442178cfa4e

**Comment by adamralph** [comment]
@ygel how about https://github.com/adamralph/simple-exec/pull/142?

**Comment by adamralph** [comment]
Closing based on https://github.com/adamralph/simple-exec/pull/142#issuecomment-524860983.

@ygel if you end up producing a package for this, I'd be interested to hear about it!

**Comment by russcam** [comment]
@ygel you might be interested in taking a look at [Proc](https://github.com/nullean/Proc), which builds on an observable Process, and seems suited to what you'd like to do here.

**Comment by russcam** [comment]
The System.Reactive (Rx) dependencies are rewritten and IL-merged into Proc, so there are [no _direct_ dependencies](https://www.nuget.org/packages/Proc/) on them.
