### ISSUE TITLE
Support passing environment vars to processes

### ISSUE THREAD

**Issue by damianh** [adamralph/simple-exec#174]
## Use case(s)

Some of our tooling (basically around yarn / npm) leverages environment variables instead of arguments and some scenarios it not possible to pass args via scripts nested in package.json. (How does software even work?)

## Description

Since simple-exec is a wrapper around `ProcessStartInfo` which already supports [`EnviromentVariables`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.environmentvariables?view=netcore-3.0) and since UseShellExecute is `false`, it should allow the caller to optionally modify before executing:

```
public static void Run(string name, ..snip... , Action<IDictionary<string, string>> configEnvironmentVariables = null);

```

Example usage:

```
Run("foo", ...snip..., env => env["bar"] = "baz");
```

## Alternatives

This is nasty yo

```
Environment.SetEnvironmentVariable("bar", "baz"); 
RunCmd("yarn", "somescript");
Environment.SetEnvironmentVariable("", ""); 
```

## Additional context

None.

**Comment by adamralph** [comment]
I like it! And I could use it to simplify the [MinVer package tests](https://github.com/adamralph/minver/blob/9ac5a56e67ef12a2751d0a2a3ba1827434864234/targets/Program.cs#L131).

**Comment by adamralph** [comment]
@damianh I've released this in [6.2.0-rc.1](https://www.nuget.org/packages/SimpleExec/6.2.0-rc.1). Can you take it for a spin?

**Comment by damianh** [comment]
I will

**Comment by adamralph** [comment]
I'm doing so too. And loving it!

- https://github.com/adamralph/liteguard/pull/312/files#diff-29155d6173e232402371c24c8b206e60R21
- https://github.com/xbehave/xbehave.net/pull/639/files#diff-29155d6173e232402371c24c8b206e60R21

**Comment by damianh** [comment]
Works here 👍 :shipit:
