### ISSUE TITLE
Add a timeout parameter to Run

### ISSUE THREAD

**Issue by mhmd-azeez** [adamralph/simple-exec#176]
## Use case(s)
It's useful for when you run a long running process and don't want to wait more than X amount of time for it to end.

## Description

Add a timeout parameter of type `TimeSpan` to the `Run` methods.

## Alternatives

A cancellation token would be nice, but I am not sure how it would be implemented, because by default [`Process.WaitForExit`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=netframework-4.8#System_Diagnostics_Process_WaitForExit_System_Int32_) only supports a timeout method.

## Additional context

I am currently creating an online document converter and use LibreOffice. I don't want to wait more than 1 minute for a document to be converted to make sure the server is not overloaded.

P.S: I am happy to send a PR if you think this is a good idea

**Comment by adamralph** [comment]
Thanks for raising this @encrypt0r! I'm a little snowed under right now, but I'll have a think about this and get back to you ASAP.

**Comment by damianh** [comment]
There are subtle complexities for handling clean process shutdowns. I invite you to look at [LittleForker](https://github.com/damianh/LittleForker) that I use for more complicated scenarios.

**Comment by adamralph** [comment]
@encrypt0r as @damianh says, it may be better for you to use [LittleForker](https://github.com/damianh/LittleForker) for your scenario instead of SimpleExec.

**Comment by encrypt0r** [comment]
LittleForker is very nice indeed. I'll close this issue.
