### ISSUE TITLE
Provide more succinct syntax for long argument lists

### ISSUE THREAD

**Issue by mungojam** [adamralph/simple-exec#190]
## Use case(s)

When running commands with more than 2-3 arguments, it can be a bit verbose to break the arguments across multiple lines, particularly when using dotnet script compared with powershell.

## Description

Make an option to remove newlines from the argument list such that consumers can use multiline literals as a more succinct way to break many arguments across multiple lines.

So instead of:

```c#
Run(
    "dotnet",
    "my-command sub-command " + 
    @"--releases-folder dist\release " +
    "--destination https://some-big-long-bucket-location " +
    @"--intermediates-folder build\something\something-else"
);
```

I could write:

```c#
Run(
    "dotnet",
    @"my-command sub-command  
    --releases-folder dist\release
    --destination https://some-big-long-bucket-location
    --intermediates-folder build\something\something-else",
    stripNewLines: true
);
```

## Alternatives

The alternative is that I add `.Replace("\r", "").Replace("\n", "")` at the end of each argument string, or make an extension method to do it like `.RemoveNewLines()`.

**Comment by adamralph** [comment]
Hi @mungojam, thanks for raising this.

I still need to give this some more thought but, right now, I'm not yet convinced that the problem of representation of long string arguments is something best solved in SimpleExec. It feels more like a general C# thing, possibly solved with something like the extension method you suggest as an alternative. Also, I'm not sure that the "..." + "..." method is so bad either. Thing is, if you ever needed to pass an argument containing a CR or LF, I guess you wouldn't be able to you were using the CR/LF replacement hack.

**Comment by mungojam** [comment]
Hi Adam, thanks for giving it some thought.  I think you're probably right and for my use case in our build scripts based on dotnet-script I'm going to need to create some common libraries anyway so I could easily wrap your method with one that replaced the newlines.

I agree that it won't allow for newlines in arguments but then those don't tend to work on the command line anyway afaik because it submits the statement.

**Comment by adamralph** [comment]
Thanks @mungojam. I'll close this for now, but if you have any more thoughts about it, please don't hesitate to write again.

BTW, here's another option:

```c#
Run(
    "dotnet",
    string.Join(
        " ",
        "my-command sub-command",
        "--releases-folder dist\release",
        "--destination https://some-big-long-bucket-location",
        "--intermediates-folder build\something\something-else"));
```

**Comment by mungojam** [comment]
Neat thanks, I think that's clear to read and more correct which would normally be my priorities. Thanks for the neat library 🙂
