### ISSUE TITLE
Add support for the CreateNoWindow option

### ISSUE THREAD

**Issue by thomaslevesque** [adamralph/simple-exec#222]
## Use case(s)

SimpleExec is great when you need to call a console app from another console app. However, when you use it from a non-console app (e.g. WPF or Windows Forms), it opens a console window for the new process, which is annoying

## Description

Adding a parameter to specify [`CreateNoWindow`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.createnowindow?view=netcore-3.1) in the `ProcessStartInfo` object would fix this.

## Alternatives

Another option would be to detect if the current process has a console window attached, and if not, set `CreateNoWindow` to true.

## Additional context

N/A

**Comment by adamralph** [comment]
hey @thomaslevesque, it sounds reasonable to me.

Is it as simple as https://github.com/adamralph/simple-exec/pull/223 ?

**Comment by thomaslevesque** [comment]
Yes, that's what I had in mind. Thanks!
