### ISSUE TITLE
ExitCodeException loses error messages

### ISSUE THREAD

**Issue by drpeck** [adamralph/simple-exec#337]
## Use case(s)

My task is failing during `Command.ReadAsync` with a `NonZeroExitCodeException` in production (Docker image running on AWS ECS). It's a nightmare to debug, because the exception doesn't contain the echo'ed text.

## Description

`ExitCodeException` could include the output

## Alternatives

We could create `Command.TryReadAsync` which doesn't through an exception but the return type would state the error code.

**Comment by adamralph** [comment]
Hi @drpeck, thanks for raising this.

It sounds like the executable you are running is not well behaved. When it fails, if there is additional diagnostic information about the faliure, in addition to the exit code, I would expect that information to be written to stderr, not stdout. Is the source code of the executable under your control? If so, I would first consider changing it to write the diagnostic information to stderr.

**Comment by drpeck** [comment]
It's not under my control unfortunately. TBH I didn't/don't really understand stderr stuff, but I have managed to add a `2> error.log` to pipe the errors to a file and I can read it from there.

It would be nice if it were handled all within managed code, but I'm sure it's not straightforward.

Thanks for your hard work.

**Comment by adamralph** [comment]
I see, so it seems that the executable _is_ well behaved, but you are invoking SimpleExec in a context where you don't see stderr in the console.

I need to give this a little more thought. This problem _may_ belong slightly outside the simple contexts that SimpleExec is designed for. I'll get back to you ASAP.

In the meantime, the workaround you are using sounds fine for now.

**Comment by adamralph** [comment]
BTW, I'm not sure I understand your listed alternative:

> We could create `Command.TryReadAsync` which doesn't through an exception but the return type would state the error code.

It doesn't seem to address the problem you are facing, and it's possible to capture the exit code and swallow the exception today:

```c#
string result;
int exitCode;

try
{
    result = Read("foo.exe");
}
catch (ExitCodeException ex) // in 7.x you have to catch NonZeroExitCodeException
{
    exitCode = ex.ExitCode;
}
```

**Comment by drpeck** [comment]
I suppose I had assumed at the time that the output wasn't returned at all with a non-zero, rather than it was possible to capture as you have above.
________________________________

**Comment by adamralph** [comment]
Well, the exception still doesn't give you the contents of stderr (or stdout). It only gives you the exit code. To be able to see the contents of stderr you need your `2> error.log` workaround (or a new feature in SimpleExec).

BTW —

> TBH I didn't/don't really understand stderr stuff...

The [Wikipedia page](https://en.wikipedia.org/wiki/Standard_streams) has a good explanation.

**Comment by adamralph** [comment]
@drpeck this will covered by https://github.com/adamralph/simple-exec/issues/351

Thanks again for raising this.
