### ISSUE TITLE
New API for version 9

### ISSUE THREAD

**Issue by adamralph** [adamralph/simple-exec#351]
## Use case(s)

All uses of the package.

## Description

A better API which makes a clear distinction between `Run`/`RunAsync`, which do NOT redirect the standard streams, and `ReadAsync`, which does. The latter gives access to standard output and standard error both in the return value from the method call, and when an exception is thrown due to a non-zero exit code.

```diff
+override SimpleExec.ExitCodeException.Message.get -> string
+override SimpleExec.ExitCodeReadException.Message.get -> string
 SimpleExec.Command
 SimpleExec.ExitCodeException
 SimpleExec.ExitCodeException.ExitCode.get -> int
 SimpleExec.ExitCodeException.ExitCodeException(int exitCode) -> void
-static SimpleExec.Command.Read(string name, string args = null, string workingDirectory = null, bool noEcho = false, string windowsName = null, string windowsArgs = null, string logPrefix = null, System.Action<System.Collections.Generic.IDictionary<string, string>> configureEnvironment = null, bool createNoWindow = false, System.Text.Encoding encoding = null, System.Func<int, bool> handleExitCode = null) -> string
-static SimpleExec.Command.ReadAsync(string name, string args = null, string workingDirectory = null, bool noEcho = false, string windowsName = null, string windowsArgs = null, string logPrefix = null, System.Action<System.Collections.Generic.IDictionary<string, string>> configureEnvironment = null, bool createNoWindow = false, System.Text.Encoding encoding = null, System.Func<int, bool> handleExitCode = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) -> System.Threading.Tasks.Task<string>
-static SimpleExec.Command.Run(string name, string args = null, string workingDirectory = null, bool noEcho = false, string windowsName = null, string windowsArgs = null, string logPrefix = null, System.Action<System.Collections.Generic.IDictionary<string, string>> configureEnvironment = null, bool createNoWindow = false, System.Func<int, bool> handleExitCode = null) -> void
-static SimpleExec.Command.RunAsync(string name, string args = null, string workingDirectory = null, bool noEcho = false, string windowsName = null, string windowsArgs = null, string logPrefix = null, System.Action<System.Collections.Generic.IDictionary<string, string>> configureEnvironment = null, bool createNoWindow = false, System.Func<int, bool> handleExitCode = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) -> System.Threading.Tasks.Task
+SimpleExec.ExitCodeReadException
+SimpleExec.ExitCodeReadException.ExitCodeReadException(int exitCode, string standardOutput, string standardError) -> void
+SimpleExec.ExitCodeReadException.StandardError.get -> string
+SimpleExec.ExitCodeReadException.StandardOutput.get -> string
+SimpleExec.Result
+SimpleExec.Result.Result(string standardOutput, string standardError) -> void
+SimpleExec.Result.StandardError.get -> string
+SimpleExec.Result.StandardOutput.get -> string
+static SimpleExec.Command.ReadAsync(string name, string args = null, string workingDirectory = null, string windowsName = null, string windowsArgs = null, System.Action<System.Collections.Generic.IDictionary<string, string>> configureEnvironment = null, System.Text.Encoding encoding = null, System.Func<int, bool> handleExitCode = null, string standardInput = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) -> System.Threading.Tasks.Task<SimpleExec.Result>
+static SimpleExec.Command.Run(string name, string args = null, string workingDirectory = null, bool noEcho = false, string windowsName = null, string windowsArgs = null, string echoPrefix = null, System.Action<System.Collections.Generic.IDictionary<string, string>> configureEnvironment = null, bool createNoWindow = false, System.Func<int, bool> handleExitCode = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) -> void
+static SimpleExec.Command.RunAsync(string name, string args = null, string workingDirectory = null, bool noEcho = false, string windowsName = null, string windowsArgs = null, string echoPrefix = null, System.Action<System.Collections.Generic.IDictionary<string, string>> configureEnvironment = null, bool createNoWindow = false, System.Func<int, bool> handleExitCode = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) -> System.Threading.Tasks.Task
```

## Alternatives

Continue with the current API.

## Additional context

This also avoids scenarios such as https://github.com/adamralph/simple-exec/issues/337 and https://github.com/adamralph/simple-exec/issues/103.

**Comment by adamralph** [comment]
@drpeck I've released this in [9.0.0-alpha1](https://www.nuget.org/packages/SimpleExec/9.0.0-alpha.1). Would you like to give it a try to see if it addresses the problems you mentioned in https://github.com/adamralph/simple-exec/issues/337?

**Comment by dariocc** [comment]
Hi! 

First of all, thanks for your work in this project which simplifies running commands.

With this change, it seems not possible to capture stdout in the result while still keep it being redirected to the console, is there?
Also, why did the synchronous `Read` stop making sense?

Thanks!

**Comment by adamralph** [comment]
Hi @dariocc, I'm glad you find the package useful!

> With this change, it seems not possible to capture stdout in the result while still keep it being redirected to the console, is there?

AFAIK that was never possible with SimpleExec. Since `Read` and `ReadAsync` were introduced, they never allowed stdout to go to the console since they capture that stream. Are you 100% sure you observed different behaviour in an earlier version? Note that in versions 8 and below, `stderr` _did_ go to the console, since it was not captured. Maybe you are thinking of that?

> Also, why did the synchronous `Read` stop making sense?

See https://github.com/adamralph/simple-exec/blob/8.0.0/SimpleExec/Command.cs#L161-L163

Note that, if you know that the sync-over-async methods are OK in your context, you can still use them:

```c#
var (standardOut, standardError) = Command.ReadAsync("foo").GetAwaiter().GetResult()
```

The point is that only _you_ know if you can do that or not. The library can't tell.

**Comment by adamralph** [comment]
> With this change, it seems not possible to capture stdout in the result while still keep it being redirected to the console, is there?

@dariocc after reading this question again, I realised that maybe I misunderstood it when writing my previous response. Are you implying that a previous version of SimpleExec provided this feature? Or is this a feature you would like in _some_ version of SimpleExec?

**Comment by dariocc** [comment]
> they never allowed stdout to go to the console since they capture that stream. 

@adamralph you are right, I meant `stderr`. I haven't really paid attention if `stdout` was redirected to the console too but it'd make sense for me that it isn't, at least by default.

> The point is that only you know if you can do that or not. The library can't tell.

Yes, I knew about this work-around and yes, I'm sure I can do it in my app as it is a simple CLI.

> I realised that maybe I misunderstood it when writing my previous response. Are you implying that a previous version of SimpleExec provided this feature?

I think I mixed things up a bit in my message. There are two things I miss in version 9.0.0:

* The possibility of redirecting the stderr stream to the console, but still be able to capture it. The use case is that capturing it and printing out afterwards does not provide the same _interactivity_ for a process that takes some time to run. Perhaps it would be possible to have a way to handle the StdErr stream from the consumer application?
I could do same sort of reasoning for Stdout. Some applications produce output to both stdout and stderr and when both are being printed to the console the output is _interleaved_, which is different than capturing output in different variables and then printing out at the end.
* I found the echoing of the command useful, since that is what I want when interacting with CLI applications. However this is easily solved in the consumer application, so not a big deal.

**Comment by adamralph** [comment]
@dariocc one way to think of the current API (version 9 and later) is _capturing_ and _non-capturing_. I.e `ReadAsync` is a _capturing_ in that it captures both stdout and stderr, and `RunAsync` (and `Run`) is _non-capturing_ in that it just runs the process without any regarding for what happens to stdout and stderr. I think this make more sense than the old API (version 8 and earlier) which was "half-capturing", in that `ReadAsync` (and `Read`) only captured stdout but not stderr.

> The possibility of redirecting the stderr stream to the console, but still be able to capture it. The use case is that capturing it and printing out afterwards does not provide the same interactivity for a process that takes some time to run. Perhaps it would be possible to have a way to handle the StdErr stream from the consumer application?
I could do same sort of reasoning for Stdout. Some applications produce output to both stdout and stderr and when both are being printed to the console the output is interleaved, which is different than capturing output in different variables and then printing out at the end.

As it happens, I'm currently experimenting with a "third way" for a future version. A kind of "reactive" API which allows your code to respond to lines written to both stdout and stderr and do what you like with them. For example, you could both add them to a `StringBuilder` and write them to the console, which would seem to satisfy your use case.

A possible design:

```c#
var output = new StringBuilder();
var error = new StringBuilder();

await Command.RunAsync(
    "foo",
    onStandardOutput: async (line, cancellationToken) =>
   {
        await Console.Out.WriteLineAsync(line);
        _ = output.AppendLine(line);
   },
    onStandardError: async (line, cancellationToken) =>
   {
        await Console.Error.WriteLineAsync(line);
        _ = error.AppendLine(line);
   });

var standardOutput = output.ToString();
var standardError = error.ToString();
```

**Comment by dariocc** [comment]
I understand the reasoning behind the distinction between Read and Run and that is fine for me. The callback method approach to handle the streams would definitely suffice for my purpose and to me, it makes sense to give that freedom to programs.

Thanks for your all your answers. I look forward to future versions with this improvement.
