### ISSUE TITLE
Can not use in Windows 10, even for simple command.

### ISSUE THREAD

**Issue by zydjohnHotmail** [adamralph/simple-exec#360]
## Version(s)
8.0
The version(s) in which you have observed the bug.

## To reproduce

Hello:
I want to try to use this repo to run some complicated FFMPEG commands, but I want to try some simple command first. However, it failed.
I created one WinForms App using Visual Studio 2019 target .Net 5.0.(x64)
I have this code:
            string simple_command = @"notepad test1.txt";
            await RunAsync(simple_command);
But when I run this, I got error:
An exception of type 'System.ComponentModel.Win32Exception' occurred in System.Private.CoreLib.dll but was not handled in user code
The system cannot find the file specified.

Not only this command, I have tried many other commands, none of them can be found by the system.
Let me know if I made any mistake.

Steps to reproduce the behaviour:
## Expected behaviour
To open a notepad and edit one file.

## Actual behaviour
Error:
The system cannot find the file specified.

A clear and concise description of what did happen.

## Workarounds
None
A clear and concise description of any workarounds you have identified.

## Additional context
None

**Comment by adamralph** [comment]
```c#
string simple_command = "notepad";
string simple_arg = "test1.txt";
await RunAsync(simple_command, simple_arg);
```
