### ISSUE TITLE
Read while displaying standard & error output in real time

### ISSUE THREAD

**Issue by stevozilik** [adamralph/simple-exec#523]
## Use case(s)

This is for scenario when asking a [credentials provider](https://github.com/microsoft/artifacts-credprovider#session-token-cache-locations) for access token. The credentials provider may ask the user to log into (via a browser window), providing the log in URL and Code via Error Output. After successful log in (or if credentials are already cached), the credentials provider outputs the access token to Standard Output. Without displaying the instruction for interactive log in, the operation just times out and fails.

## Description

Introduce a Read Command (override) that would enable displaying the Standard & Error Output in real time, e.g. passing on the OutputDataReceived/ErrorDataReceived event and let us choose if we want to Console.WriteLine(...) the existing output.

**Comment by adamralph** [comment]
@stevozilik thank you for raising this. I'm not yet sure if this something I want to introduce and maintain, but I'm taking it under consideration.

**Comment by adamralph** [comment]
@stevozilik I want to ensure I understand the use case. As I understand it, you would like to use SimpleExec to run an external process which is a credentials provider. That external process may or may not open a browser window, and then it writes an access token to standard output. Assuming that the external process then exits, I'm not sure why this doesn't work for you. Why do you need to read standard output while the process is running? Does it not exit?

**Comment by adamralph** [comment]
Closing as the use case doesn't seem to make sense.
