### ISSUE TITLE
Reg Query Error!

### ISSUE THREAD

**Issue by gokanil** [adamralph/simple-exec#533]
I get an error when I run the command below.

Run("CMD", "Reg Query \"HKEY_LOCAL_MACHINE\SOFTWARE\GitForWindows\"", noEcho: false, createNoWindow: false, handleExitCode: code => { return true; });

ERROR: The system was unable to find the specified registry key or value.

**Comment by gokanil** [comment]
The problem was that it worked with 32 bit. It was fixed when 64 bit.

**Comment by adamralph** [comment]
> The system was unable to find the specified registry key or value

What does that tell you?

**Comment by adamralph** [comment]
This doesn't seem like a problem with SimpleExec. The fact that an error message is returned from the command demonstrates that the command _is_ being executed, but on of the arguments it is being passed (the path to a registry key) is invalid (the registry key doesn't exist).
