### ISSUE TITLE
Providing the possibility to kill not only a process, but also child processes. 

### ISSUE THREAD

**Issue by Amadeeo** [adamralph/simple-exec#541]
## Use case(s)

Sometimes when a process runs other processes there is requirement to kill also child processes.

## Description

This feature can be simply implemented to method `private static bool TryKill(this Process process`) in a class `ProcessExtensions.cs` by adding flag _true_ to `process.Kill(true);` The flag can be set optionally by the programmer.

**Comment by adamralph** [comment]
Thanks for raising this. I'll look into it ASAP.

**Comment by adamralph** [comment]
FTR, the [`Process.Kill(boolean)`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=net-7.0#system-diagnostics-process-kill(system-boolean)) overload is only available in .NET 8.

**Comment by adamralph** [comment]
FYI this will be added after .NET 8 is RTM.

**Comment by adamralph** [comment]
@Amadeeo thanks again for raising this, I've reshaped it as #600
